<a href="https://colab.research.google.com/github/noamsw/TensorFlow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
#create a 0D tensor
tensor_0D = tf.constant(4)
print(tensor_0D)
#notice that the tensor has no shape

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#create a 1d tensor
tensor_1D = tf.constant([2.0,0,-3])
#notice how the tensor now has a shape
#and the whole datatype is determined by a single float
print(tensor_1D)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [ ]:
#create a 2D tensor
tensor_2D = tf.constant([
    [0,2,3],
    [1,-9,3.0],
])
#again notice the dtype
print(tensor_2D)

tf.Tensor(
[[ 0.  2.  3.]
 [ 1. -9.  3.]], shape=(2, 3), dtype=float32)


In [ ]:
#create a 3D tensor
tensor_3D = tf.constant([
    [[2,3],
     [3,-1]],
    [[7,4],
     [12,-1]],
    [[12,32],
     [30,-1.0]],
])
print(tensor_3D)

tf.Tensor(
[[[ 2.  3.]
  [ 3. -1.]]

 [[ 7.  4.]
  [12. -1.]]

 [[12. 32.]
  [30. -1.]]], shape=(3, 2, 2), dtype=float32)


In [ ]:
#we can view only the shape:
print(tensor_3D.shape)
#or its num of dimensions:
print(tensor_2D.ndim)

(3, 2, 2)
2


In [ ]:
#how do we constuct a 4D tensor?
#this, like before, is simply several 3D tensors.
#a good way of thinking of it, is time
#imagine the 3D is a 3D representation of space
#and the 4D is the same space through time

In [ ]:
#create a 4D tensor
tensor_4D = tf.constant([
    [[[2,3],
     [3,-1]],
     [[-7,4],
     [12,-1]],
     [[12,32],
     [360,-1.0]]],
    [[[2,3],
     [3,-1]],
     [[7,4],
     [12,-1]],
     [[212,32],
     [30,-1.0]]],
    [[[2,3],
     [32,-1]],
     [[7,64],
     [112,-1]],
     [[12,32],
     [30,-1.0]]],
])
print(tensor_4D)

tf.Tensor(
[[[[  2.   3.]
   [  3.  -1.]]

  [[ -7.   4.]
   [ 12.  -1.]]

  [[ 12.  32.]
   [360.  -1.]]]


 [[[  2.   3.]
   [  3.  -1.]]

  [[  7.   4.]
   [ 12.  -1.]]

  [[212.  32.]
   [ 30.  -1.]]]


 [[[  2.   3.]
   [ 32.  -1.]]

  [[  7.  64.]
   [112.  -1.]]

  [[ 12.  32.]
   [ 30.  -1.]]]], shape=(3, 3, 2, 2), dtype=float32)


In [ ]:
#Tensors are multidimensional
#we can continue to add dimensions to the tensor as we go along
#there is no real limit. It should be an excersise to the reader to decide what higher dimensions mean
#for instance 5 dimensions may be the same space, during different times, in different experiments

In [ ]:
#we can choose the datatype of the tensor
tensor_0D = tf.constant(4, dtype=tf.float32)
print(tensor_0D)
# the float type determine how much memory the tensor takes.
#higher precision requires more memory
#for memory constraints we would like to lower precision

tf.Tensor(4.0, shape=(), dtype=float32)


In [ ]:
# you can also cast a tensor to a different dtype
casted_tensor = tf.cast(tensor_0D, dtype=tf.int64)
binary_casted_tensor = tf.cast(tensor_0D, dtype=tf.bool)
print(casted_tensor)
print(binary_casted_tensor)


tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(True, shape=(), dtype=bool)


In [ ]:
# there are string tensors as well
tensor_string = tf.constant(["helloWorld"], dtype=tf.string)
print(tensor_string)

tf.Tensor([b'helloWorld'], shape=(1,), dtype=string)


In [ ]:
# converting numpy arrays to tensors:
import numpy as np
np_array = np.array([2,2,3])

In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([2 2 3], shape=(3,), dtype=int64)


In [ ]:
# creating an identity tensor
eye_tensor = tf.eye(num_rows=3, num_columns=4)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
# you can mutliply tensor by a scaler:
multiplied_tensor = 3 * eye_tensor
print(multiplied_tensor)

tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
# creating an identity tensor and using the batch shape
eye_tensor = tf.eye(num_rows=3, batch_shape=[2,3,])
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 3, 3, 3), dtype=float32)


In [ ]:
# tensor fill - create a tensor filled with a scalar value
filled_tensor = tf.fill([1,3,4], 5)
filled_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]], dtype=int32)>

In [ ]:
# create a tensor with values set to 1
ones_tensor = tf.ones([3,4])
ones_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all ones, the same shape as input
oned_tensor = tf.ones_like(filled_tensor)
oned_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [ ]:
# a zeros tensor, zeros_like method exists as well
zeros_tensor = tf.zeros([1,3,4])
zeros_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# return a tensor that contains the shape of the tensor
shape_tensor = tf.shape(zeros_tensor)
shape_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4], dtype=int32)>

In [ ]:
# the rank of a tensor, which the ndims, not the rank of a matrix
# it can be thought of the min number of indicies required to select a specific element
tf.rank(zeros_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# return a tensor containing the size of a tensor
# you can specify the out_type
size_tensor = tf.size(zeros_tensor)
size_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# create a tensor filled with random values from a normal distribution
normal_tensor = tf.random.normal([2,3], mean=30.0, stddev=1.0)
normal_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[32.406475, 30.137728, 29.58299 ],
       [29.70774 , 31.498194, 29.891636]], dtype=float32)>

In [ ]:
# create a tensor with a uniform distribution
# maxval is 1 by default
# you can set the seed in order to create a reproducable series of tensor
uniform_tensor = tf.random.uniform([2,5], minval=0, maxval=10, dtype=tf.int32)
uniform_tensor

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 4, 8, 4, 4],
       [2, 9, 6, 7, 1]], dtype=int32)>

In [ ]:
# setting the seed to reproduce random results
tf.random.set_seed(5)
rand1_tensor = tf.random.normal([2,3], mean=0, stddev=1, seed=4)
print(rand1_tensor)
tf.random.set_seed(5)
rand2_tensor = tf.random.normal([2,3], mean=0, stddev=1, seed=4)
print(rand2_tensor)

tf.Tensor(
[[-0.13512394  0.57511264  1.328877  ]
 [ 0.37756917 -0.9809903   0.0878263 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.13512394  0.57511264  1.328877  ]
 [ 0.37756917 -0.9809903   0.0878263 ]], shape=(2, 3), dtype=float32)
