<a href="https://colab.research.google.com/github/noamsw/TensorFlow/blob/main/TensorFlow3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# adding dimensions to a tensor:
tensor = tf.constant([[1,2,3],
                      [4,5,6]])
print(tensor.shape)
print(tf.expand_dims(tensor, axis=-1).shape)

(2, 3)
(2, 3, 1)


In [3]:
# squeeze or lowering dimension
# removes all dimensions of size 1
tensor = tf.constant([[[[1,2,3],
                      [4,5,6]]]])
print(tensor.shape)
print(tf.squeeze(tensor,axis=0).shape)
# if you dont specify an axis, it will squeeze all dimensions of 1
print(tf.squeeze(tensor).shape)

(1, 1, 2, 3)
(1, 2, 3)
(2, 3)


In [4]:
# we can alo reshape to resqueeze
print(tf.reshape(tensor, (2,3)))
# we can also reshape it into a 1D array
print(tf.reshape(tensor, (6)))
print(tf.reshape(tensor, (3,2)))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [5]:
# if you dont know the size of the last dimension, use -1
print(tf.reshape(tensor, (3,-1)))
print(tf.reshape(tensor, (-1)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [6]:
# we can concatenate tensors along an axis, the size of that axis must match
t1 = tf.squeeze(tensor)
t2 = tf.constant([[7,8,9]])
# 0 is along the rows, 1 alog the columns
tf.concat([t1, t2], 0)
# in order to concatenate along columns, the second dimension must match
t2 = tf.constant([[7,8],
                  [10,11]])
tf.concat([t1, t2], 1)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6, 10, 11]], dtype=int32)>

In [7]:
# stack, which simply adds the two tensors together
t2 = tf.constant([[7,8,9],
                  [10,11,12]])
print(tf.stack([t1,t2], axis = 0))
print(tf.stack([t1,t2], axis = 1))
# it simply tells us were we add up the dimensions
# it is clearer with more tensors
# we have tensors of size (2,3)
# if we add 3 on the 0 dimension, we get (3,2,3)
# if we add 3 on the 1 axis, we get (2,3,3)
# if we add 3 on the 2 axis, we get (2,3,3)
print(tf.stack([t1,t1,t2], axis = 0))
print(tf.stack([t1,t1,t2], axis = 1))
print(tf.stack([t1,t1,t2], axis = 2))


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 4  5  6]
  [10 11 12]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[ 1  1  7]
  [ 2  2  8]
  [ 3  3  9]]

 [[ 4  4 10]
  [ 5  5 11]
  [ 6  6 12]]], shape=(2, 3, 3), dtype=int32)


In [11]:
# paddings, which will pad with a value to a certain size
# here we tell the paddings function how many rows to pad
# and how many columns to pad before and after
paddings = tf.constant([[1,2], [2,3]])
tensor = tf.constant([[1,2,3],
                      [4,5,6]])
# the default is 0
tf.pad(tensor, paddings)

<tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [9]:
# we can change it to whatever
tf.pad(tensor, paddings, constant_values = 3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [13]:
# tf gather is a way to access indecis
tensor = tf.constant([1,2,3,4,5,6])
# we can access with classic access operators
tensor[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [15]:
# we can use gather
tf.gather(tensor, tf.range(1,3))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [18]:
# lets play with it a bit
tf.gather(tensor, [0,5,2])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 6, 3], dtype=int32)>

In [20]:
tensor = tf.constant([[1,2,3],
                      [4,5,6]])
# the default axis is 0
tf.gather(tensor, [0])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [29]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                      ])
# the default axis is 0
print(tensor.shape)
tf.gather(tensor, [1,0], axis = 1)

(2, 2, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[10, 11, 12],
        [ 7,  8,  9]]], dtype=int32)>

In [37]:
# gather_nd is like gather, but we can change the ouptut shape
params = [[["a0","b0"],
          ["c0","d0"]],
          [["a1","b1"],
           ["c1","d1"]]]
indices = [[0],
           [1]]
tf.gather_nd(params, indices)
# we take the 0 and 1 element from the array

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'a0', b'b0'],
        [b'c0', b'd0']],

       [[b'a1', b'b1'],
        [b'c1', b'd1']]], dtype=object)>

In [33]:
# lets take 1,1
indices = [[1,1]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'd'], dtype=object)>

In [35]:
# lets take 01 and 10
indices = [[0,1], [1,0]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b', b'c'], dtype=object)>

In [41]:
# the resulting shape is also determined by the indicis
indices = [[[0,1],
            [1,0]],

           [[1,1],
            [0,0]]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'c1', b'd1'],
        [b'a0', b'b0']]], dtype=object)>

In [45]:
#lets look at the batch dims argument, by default is 0
indices = [[0,1],
           [1,0]]
print(tf.gather_nd(params, indices))
print(tf.gather_nd(params, indices, batch_dims=0))

tf.Tensor(
[[b'c0' b'd0']
 [b'a1' b'b1']], shape=(2, 2), dtype=string)
tf.Tensor(
[[b'c0' b'd0']
 [b'a1' b'b1']], shape=(2, 2), dtype=string)


In [46]:
# lets change the parameter
tf.gather_nd(params, indices, batch_dims=1)
# what happened here? we tell the function that there are nultiple batches,
# and elements in the indices are for eatch batch

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>

In [51]:
# ragged tensors
# until now we have had square tensors
tensor = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9,],
                      [10,11,12]])
# but sometimes we dont want rectangular tensors
ragged =  [[1,],
          [2,3,4,5,6],
          [7,8,],
          [9,10,11,12]]
# here is were rgged tensors come in
ragged_tensor = tf.ragged.constant(ragged)
print(ragged_tensor)
# the shape is none on the none rectangular axis
print(ragged_tensor.shape)

<tf.RaggedTensor [[1], [2, 3, 4, 5, 6], [7, 8], [9, 10, 11, 12]]>
(4, None)


In [56]:
# we can easily mask data
# either make an exact mask
ragged =  [[1,],
          [2,3,4,5,6],
          [7,8,]]
# only the data that is masked with true will be saved
ragged_tensor = tf.ragged.constant(ragged)
tf.ragged.boolean_mask(
    ragged_tensor,
    tf.ragged.constant(([[True],[True,False,False,True,True],[True,False]]))
)


<tf.RaggedTensor [[1], [2, 5, 6], [7]]>

In [58]:
# one can also give a single value for each row:
tf.ragged.boolean_mask(
    ragged_tensor,
    tf.ragged.constant([True, False, True])
)
# here the second row was ignored

<tf.RaggedTensor [[1], [7, 8]]>

In [64]:
# lets look at tf.from_row_limits
print(tf.RaggedTensor.from_row_lengths(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths = [4,0,0,3,1,0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [], [5, 9, 2], [6], []]>


In [68]:
# lets look at tf.from_row_limits
print(tf.RaggedTensor.from_row_limits(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_limits = [4,4,7,8,8]
))
# here we continue breaking apart the values by limits
# if we stay at the same position, we get an empty list as we have alreasdy used it
# we have 0->4, 4->4, 4->7 etc

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [69]:
# lets look at tf.from_row_splits
print(tf.RaggedTensor.from_row_splits(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_splits = [0,4,4,7,8,8]
))
# we have 0->4, 4->4, 4->7, 7->8, 8->8

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [71]:
# we can also take only certain parts from a tensor, creating a ragged tensor
tensor = tf.constant([[1,2,3],[4,5,6], [7,8,9]])
tf.RaggedTensor.from_tensor(tensor, lengths = [1,0,3])

<tf.RaggedTensor [[1], [], [7, 8, 9]]>

In [74]:
# we may deal with tensor with many 0s
# we will want to use sparse tensor
sparse_tensor = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]],
    values = [11,56],
    dense_shape = [5,6]
)
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [75]:
# how to map to a tensor
# here we see that we said at 1,1 the value is 11 and at 3,4 56
# and shape 5,6. which is what we got
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [77]:
# String Tensors
string_tensor = tf.constant(["Hello", "World"])
string_tensor

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>

In [82]:
# join method, with a specified seperator
tf.strings.join(string_tensor, separator='/')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello/World'>

In [ ]:
# we have lenght, lower, and many more